version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/moospire-backend.conf:/etc/nginx/sites-available/moospire-backend;
    command: >
      /bin/sh -c "ln -sf /etc/nginx/sites-available/moospire-backend /etc/nginx/sites-enabled/ && nginx -g 'daemon off;'"
  moospire-server:
    build:
      context: .
  redis:
    image: redis:alpine