// ALLOWED_ORIGINS=
// API_VERSION=
// APP_CLIENT_BASE_DOMAIN=
// APP_ENV=
// APP_PORT=
// APP_SECRET=

// CLOUDINARY_CLOUD_NAME=
// CLOUDINARY_API_KEY=
// CLOUDINARY_API_SECRET=
// CLOUDINARY_UPLOAD_PRESET=

// GOOGLE_CLIENT_ID=
// GOOGLE_CLIENT_SECRET=

// FIGMA_CLIENT_ID=
// FIGMA_CLIENT_SECRET=

// EMAIL_PROVIDER=

// # Mailgun settings
// MAILGUN_API_KEY=
// MAILGUN_DOMAIN=

// # SMTP settings
// SMTP_SERVICE=
// SMTP_USER=
// SMTP_PASS=
// EMAIL_DOMAIN=

// MONGODB_USER=
// MONGODB_PASSWORD=
// MONGODB_DATABASE=

// REDIS_HOST=
// REDIS_PORT=

// SALT_ROUND=
// TOKEN_LIFE=
// OTP_TIME_TO_LIFE=
// SUPER_ADMIN_EMAIL=
